/* empty css                      */import{S as a,N as f}from"./assets/vendor-wKantkHV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const h=[{selector:".features-swiper",slideClass:"features-swiper-slide",wrapperClass:"features-swiper-wrapper"},{selector:".reviews-swiper",slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper"},{selector:".characters-swiper",slideClass:"characters-swiper-slide",wrapperClass:"characters-swiper-wrapper"},{selector:".spud-swiper",slideClass:"spud-swiper-slide",wrapperClass:"spud-swiper-wrapper",navigation:{nextEl:".spud-nav .custom-next",prevEl:".spud-nav .custom-prev"}}],l={};function p(){const n=window.innerWidth;h.forEach(t=>{const i=document.querySelector(t.selector);if(!i)return;const r=t.selector;if(l[r]&&(l[r].destroy(!0,!0),delete l[r]),t.selector===".features-swiper"){if(n<1439){const e=new a(i,{slidesPerView:1.6,spaceBetween:20,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal"});l[r]=e}}else if(t.selector===".reviews-swiper"){if(n<1439){const e=new a(i,{slidesPerView:1.1,spaceBetween:20,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal"});l[r]=e}}else if(t.selector===".characters-swiper"){if(n<1439){const e=new a(i,{slidesPerView:1,spaceBetween:20,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal"});l[r]=e}}else if(t.selector===".spud-swiper"){const e=new a(i,{modules:[f],loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal",navigation:t.navigation,observer:!0,observeParents:!0,breakpoints:{374:{slidesPerView:1.1,spaceBetween:20},1440:{slidesPerView:4,spaceBetween:20}}});l[r]=e}})}document.addEventListener("DOMContentLoaded",p);window.addEventListener("resize",()=>{clearTimeout(window._swiperResizeTimeout),window._swiperResizeTimeout=setTimeout(p,300)});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),t=n.querySelector(".icon"),i=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let s=!1;const o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="#161616" />
</svg>
    `,c=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#442C2E" />
</svg>
    `;n.addEventListener("click",()=>{s=!s,t.innerHTML=s?c:o,s?u():d()}),r.forEach(m=>m.addEventListener("click",()=>{d(),t.innerHTML=o,s=!1})),window.addEventListener("scroll",w);function u(){i.style.display="block"}function d(){i.style.display="none"}function w(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const r=document.getElementById("site-header");return r?r.offsetHeight:0}function t(r){const e=document.getElementById(r);if(!e)return;const s=n(),o=e.getBoundingClientRect().top+window.pageYOffset-s;window.scrollTo({top:o,behavior:"smooth"})}if(location.pathname.endsWith("index.html")||location.pathname==="/"||location.pathname==="/index"){document.querySelectorAll('a[href*="#"]').forEach(e=>{e.addEventListener("click",s=>{const o=e.getAttribute("href"),c=o.split("#")[1];(o.startsWith("#")||o.startsWith("index.html#")||o.startsWith("/index.html#"))&&(s.preventDefault(),t(c))})});const r=window.location.hash;if(r){const e=r.substring(1),s=()=>{document.getElementById(e)?t(e):requestAnimationFrame(s)};setTimeout(s,100)}}});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),t=document.getElementById("accept-cookies"),i=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),t.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),i.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});
//# sourceMappingURL=index.js.map
